services:
  app:
    build: .
    container_name: app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mailpit
    volumes:
      - ./:/app


  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - .env.db
    volumes:
      - pgdata:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "8025:8025" 
      - "1025:1025" 
      - "143:143"      
    restart: unless-stopped
    volumes:
      - ./data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1


volumes:
  pgdata:
  mailpit:
